header:
  version: 11
machine: raspberrypi0-2w-64
distro: velaos
defaults:
  repos:
    refspec: honister
local_conf_header:
  meta-chprat: |
    INHERIT += "rm_work"
    RPI_USE_U_BOOT = "1"
repos:
  meta-chprat:
    path: "sources/meta-chprat"
  meta-raspberrypi:
    url: "https://git.yoctoproject.org/git/meta-raspberrypi"
    path: "sources/meta-raspberrypi"
    layers:
      .:
  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    path: "sources/meta-openembedded"
    layers:
      meta-networking:
      meta-oe:
      meta-python:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    path: "sources/poky"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-swupdate:
    url: "https://github.com/sbabic/meta-swupdate.git"
    path: "sources/meta-swupdate"
    layers:
      .:
